apiVersion: comcast.github.io/v1
kind: KuberhealthyCheck
metadata:
  name: namespace-kh-check
  namespace: kuberhealthy
spec:
  runInterval: 30s # The interval that Kuberhealthy will run your check on
  timeout: 2m # After this much time, Kuberhealthy will kill your check and consider it "failed"
  podSpec: # The exact pod spec that will run.  All normal pod spec is valid here.
    containers:
      - env: # Environment variables are optional but a recommended way to configure check behavior
        image: ministryofjustice/namespace-kh-check:latest
        imagePullPolicy: Always # During check development, it helps to set this to 'Always' to prevent on-node image caching.
        name: main
        securityContext:
          runAsUser: 999
