# namespace kuberhealthy check
apiVersion: comcast.github.io/v1
kind: KuberhealthyCheck
metadata:
  name: namespace-kh-check
  namespace: kuberhealthy
spec:
  runInterval: 5m # The interval that Kuberhealthy will run your check on
  timeout: 15m # After this much time, Kuberhealthy will kill your check and consider it "failed"
  podSpec: # The exact pod spec that will run.  All normal pod spec is valid here.
    containers:
      - env: [] # Environment variables are optional but a recommended way to configure check behavior
        image: 754256621582.dkr.ecr.eu-west-2.amazonaws.com/webops/cloud-platform-kuberhealthy-checks:1.4
        imagePullPolicy: IfNotPresent 
        name: main
        securityContext:
          runAsUser: 999
    serviceAccountName: namespace-check-sa

