name: Build and Push kuberhealthy check images
on:
  workflow_dispatch:
  release:
    types: [published]

  push:
    branches:
      - "*"

jobs:
  main:
    name: Push images to docker hub
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Tag reference
        id: tag_name
        run: |
          echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}
      - name: Push namespace-check to docker hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          path: cmd/namespace-check
          repository: ministryofjustice/cloud-platform-kuberhealthy-namespace-check:${{ steps.tag_name.outputs.SOURCE_TAG }}
          tag_with_ref: true
      - name: scan docker image for vulnerabilities
        run: curl -s https://ci-tools.anchore.io/inline_scan-v0.6.0 | bash -s -- -p -r ministryofjustice/cloud-platform-kuberhealthy-namespace-check:${{ steps.tag_name.outputs.SOURCE_TAG }}